// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhJxI5pG8D40Kz8gFyAPqL9STsNqBiMDY',
    appId: '1:460955121194:web:5f3e62a47f33c5d91ab553',
    messagingSenderId: '460955121194',
    projectId: 'task-tracker-a5914',
    authDomain: 'task-tracker-a5914.firebaseapp.com',
    storageBucket: 'task-tracker-a5914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe7jz49MoI0Okp2R-loj3tSYa5UkHsvrY',
    appId: '1:460955121194:android:dbd6252fc36fb62e1ab553',
    messagingSenderId: '460955121194',
    projectId: 'task-tracker-a5914',
    storageBucket: 'task-tracker-a5914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM9vYQ4sxf1qlfZmx5YhKj-2EfKQnTFqc',
    appId: '1:460955121194:ios:f7e1fbfc882be1cd1ab553',
    messagingSenderId: '460955121194',
    projectId: 'task-tracker-a5914',
    storageBucket: 'task-tracker-a5914.appspot.com',
    iosBundleId: 'com.example.script05TaskTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM9vYQ4sxf1qlfZmx5YhKj-2EfKQnTFqc',
    appId: '1:460955121194:ios:2f947691798f9e0a1ab553',
    messagingSenderId: '460955121194',
    projectId: 'task-tracker-a5914',
    storageBucket: 'task-tracker-a5914.appspot.com',
    iosBundleId: 'com.example.script05TaskTrackerApp.RunnerTests',
  );
}
